services:
  reranker:
    container_name: reranker_service
    build: . 
    
    ports:
      # Maps host port 5656 to container port 5656
      - "5656:5656"
      
    environment:
      # This overrides the Dockerfile's ENV and sets the port gunicorn binds to
      RERANKER_PORT: 5656

      MODEL_NAME: "cross-encoder/ms-marco-MiniLM-L12-v2"
      
      BATCH_SIZE: 32

      GUNICORN_WORKERS: 2
    
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
      
    # networks:
    #   - shared_app_network 
    dns:
      - 8.8.8.8
      - 8.8.4.4